### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by Meliodas1k** [rtxpower/rtxpoweer#1]
Hi bro, can u tell me how use this?

**Comment by wanda321** [comment]
do not use it idi0t because it is virus

if you injected it to your leauge then congratulations, you have been ratted!
change your passwords and reinstall your windows

**Comment by Ljhrwmn** [comment]
> do not use it idi0t because it is virus
> 
> if you injected it to your leauge then congratulations, you have been ratted! change your passwords and reinstall your windows

Don’t talk nonsense, it is almost impossible to be hacked just by injecting a DLL into an executable. This ‘script’ apparently is a cracked or old version of BGX and btw it is only available on the CN server. However, it works normally.

**Comment by rtxpower** [comment]
> do not use it idi0t because it is virus
> 
> if you injected it to your leauge then congratulations, you have been ratted! change your passwords and reinstall your windows

kinda funny hater :)

its not virus and its not even packed you can analyse whatever you want its free trial for now.
runs all of the plugins smooth.
https://rtxpower.com/

**Comment by rtxpower** [comment]
the "bgx" moderators will keep telling users that its a virus. cuz they don't want to lose money :)

"rtxpower" script is 1:1 version of bgx and its not crack it has it own core, just runs plugins from other platforms.

you can join discord and see yourself : https://discord.gg/rtxpower
